---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    gather_facts: no
    project_id: "PRT-00"                    ## <-- 개인별 프로젝트 ID값 사용 
    vcenter_hostname: "192.168.3.10"
    vcenter_username: "s00@vclass.reca2"    ## <-- 개인별 vSphere 계정 사용 
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    esxi_hostname: "esxi-05.vclass.reca2"  ## <-- 개인별 실습 물리서버 사용 
    esxi_username: "root"
    esxi_password: "VMware1!"
    public_net:  "VM-192.168.3.x"
    private_net: "{{ project_id + '-Openshift' }}"
    parent_folder: "4.Projects"
    folder_prefix: "/Datacenter/vm/4.Projects/"
    datastore_name: "ESXi-05"              ## <-- 개인별 실습 서버의 저장소
    iso_folder: '[ESXi-05]\ISO\'

  tasks: 
    - name: 09. Create a Project VMs (aka Barametal Machines) 
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix + project_id }}'

        name: '{{ item.vmname }}'
        state: poweredon
        guest_id: '{{ item.guest_id }}'
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          num_cpus: '{{ item.cpus }}'
          memory_mb: '{{ item.memory }}'
          scsi: paravirtual
        disk:
        - size_gb: '{{ item.disk_gb }}'
          type: thin
          datastore: '{{ datastore_name }}'
        networks:
        - name: '{{ private_net }}'
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '{{ iso_folder + item.iso }}'
      loop:
      - { vmname: "{{ project_id + '-Bastion'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: rhel-8.5-x86_64-dvd.iso }
      - { vmname: "{{ project_id + '-Bootstrap'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: rhel-8.5-x86_64-dvd.iso }
      - { vmname: "{{ project_id + '-Master-01'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      - { vmname: "{{ project_id + '-Master-02'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      - { vmname: "{{ project_id + '-Master-03'}}", guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      - { vmname: "{{ project_id + '-Worker-01'}}", guest_id: rhel8_64Guest, cpus: 2, memory: 8192, disk_gb: 120, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      - { vmname: "{{ project_id + '-Worker-02'}}", guest_id: rhel8_64Guest, cpus: 2, memory: 8192, disk_gb: 120, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      - { vmname: "{{ project_id + '-Worker-03'}}", guest_id: rhel8_64Guest, cpus: 2, memory: 8192, disk_gb: 120, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      - { vmname: "{{ project_id + '-Storage'}}", guest_id: freebsd64Guest, cpus: 4, memory: 16384,  disk_gb: 32, iso: rhcos-4.12.17-x86_64-live.x86_64.iso }
      delegate_to: localhost
      register: deploy_vm
