---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    gather_facts: no
    project_id: "PRT-00"
    vcenter_hostname: "192.168.3.10"
    vcenter_username: "s00@vclass.reca2"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "4.Projects"
    folder_prefix: "/Datacenter/vm/4.Projects/"
    esxi_hostname: "esxi-05.vclass.reca2"
    esxi_password: "VMware1!"
    esxi_username: "root"
    public_net: "VM-192.168.3.x"
    private_net: "{{ project_id + '-Openshift' }}"
    datastore_name: "ESXi-05"

  tasks: 

    - name: 05. Create a Router VM with ISO file mount
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'

        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix + project_id }}'
        name: "{{ project_id + '-Router' }}"

        esxi_hostname: "{{ esxi_hostname }}"
        
        datastore: '{{ datastore_name }}'

        guest_id: "otherLinux64Guest"
        
        hardware:
          num_cpus: "1"
          memory_mb: "1024"
          scsi: paravirtual

        disk:
        - size_gb: 10
          type: thin
          
        networks:
        - name: '{{ public_net }}'
          device_type: vmxnet3
        - name: '{{ private_net }}'
          device_type: vmxnet3
          
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '[ESXi-05]\ISO\vyos-rolling-latest.iso'
          
        state: poweredon
      delegate_to: localhost
      register: deploy_vm

